site_name: tctsti
site_description: Library for benchmarking the impact of transcript count type stratification on trajectory inference.

repo_url: https://github.com/pyrovelocity/tctsti
repo_name: pyrovelocity/tctsti

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: blue grey
          accent: deep orange
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue grey
          accent: deep orange
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.10/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - src/tctsti

nav:
    - About: index.md
    - Specification: specification.md
    - Reference:
        - tctsti: reference/tctsti.md
